name: Package
on: [push]

jobs:
  build:
    name: Package
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: sudo apt-get install -y libtool bison flex devscripts debhelper
      - name: Package filebench
        run: |
          tar --exclude-vcs -zcvf '../filebench_1.5-prerelease.orig.tar.gz' --transform='s/^\./filebench/' .
          debuild -us -uc
